from addict import Dict

config_list = [
    ########## Q1 Config ###########
    {
        "name": "Q1",
        "ch": {
            "res_ch": 0,
            "qb_ch": 5,
            "ro_ch": 0,
        },
        "res": {
            "res_freq_ge": 5351.559,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
            "nqz_res": 2,
            "chi": False,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4000,
            "qb_mixer": 4000,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "ramsey_freq": 2,
            "nqz_qubit": 1,
        },
        "cooling": {
            "cooling": False,
            "cool_ch1": 2,
            "cool_freq_1": 5400,
            "cool_gain_1": 0.1,
            "nqz_cool_ch1": 2,
            "cool_length": 100,
            "cool_ch2": 3,
            "cool_freq_2": 5400,
            "cool_gain_2": 0.1,
            "nqz_cool_ch2": 2,
        },
        "reps": 100,
        "trig_time": 0.5,
        "relax_delay": 10,
    },
    ########## Q2 Config ###########
    {
        "name": "Q2",
        "ch": {
            "res_ch": 0,
            "qb_ch": 6,
            "ro_ch": 0,
        },
        "res": {
            "res_freq_ge": 5490.218,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4000,
            "qb_mixer": 4000,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "ramsey_freq": 2,
        },
        "reps": 100,
        "trig_time": 0.75,
        "relax_delay": 10,
    },
    ########## Q3 Config ###########
    {
        "name": "Q3",
        "ch": {
            "res_ch": 0,
            "qb_ch": 6,
            "ro_ch": 0,
        },
        "res": {
            "res_freq_ge": 5668.587,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4000,
            "qb_mixer": 4000,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "ramsey_freq": 2,
        },
        "reps": 100,
        "trig_time": 0.75,
        "relax_delay": 10,
    },
    ########## Q4 Config ###########
    {
        "name": "Q4",
        "ch": {
            "res_ch": 0,
            "qb_ch": 7,
            "ro_ch": 0,
        },
        "res": {
            "res_freq_ge": 5797.46,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4000,
            "qb_mixer": 4000,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "ramsey_freq": 2,
        },
        "reps": 100,
        "trig_time": 0.75,
        "relax_delay": 10,
    },
    ########## Q5 Config ###########
    {
        "name": "Q5",
        "ch": {
            "res_ch": 0,
            "qb_ch": 6,
            "ro_ch": 0,
        },
        "res": {
            "res_freq_ge": 5917.51,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4000,
            "qb_mixer": 4000,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "ramsey_freq": 2,
        },
        "reps": 100,
        "trig_time": 0.75,
        "relax_delay": 10,
    },
    ########## Q6 Config ###########
    {
        "name": "Q6",
        "ch": {
            "res_ch": 0,
            "qb_ch": 6,
            "ro_ch": 0,
        },
        "res": {
            "res_freq_ge": 6051.89,
            "res_length": 10,
            "res_gain_ge": 0.1,
            "res_phase": 0,
            "res_sigma": 0.005,
            "ro_length": 5,
        },
        "qb": {
            "pulse_type": "arb",
            "qb_freq_ge": 4000,
            "qb_mixer": 4000,
            "qb_gain_ge": 0.1,
            "qb_phase": 0,
            "sigma": 0.05,
            "pi_gain_ge": 0.1,
            "pi2_gain_ge": 0.1,
            "qb_flat_top_length_ge": 0.1,
            "ramsey_freq": 2,
        },
        "reps": 100,
        "trig_time": 0.75,
        "relax_delay": 10,
    },
]


config_addict = [Dict(d) for d in config_list]
mux_phases = [item.res.res_phase for item in config_addict]
mux_res_freq = [item.res.res_freq_ge for item in config_addict]
mux_ch = 12
mux_ro_ch = [2, 3, 4, 5, 6, 7]
